name: Release XCFramework
on:
  pull_request:
    types: [ labeled ]
  push:
    tags:
      - '*'

jobs:
  release_xcframework:
    name: Release XCFramework
    if: ${{ (github.event.number > 0 && github.event.label.name == 'Release XCFramework') || github.event.number == 0 }}
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
      HOMEBREW_NO_AUTO_UPDATE: 1
      xcframeworks_output_path: 'outputs/xcframeworks'

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create XCFrameworks
        uses: mohamed-3amer/swift-create-xcframework@main
        with:
          target: 'ParallaxPagerView'
          zip-version: ${{ github.event.number == 0 && github.ref_name || format('{0}-pr', github.event.number) }}
          zip-checksum-output-path: ${{ env.xcframeworks_output_path }}
          upload-to-artifacts: false

      - name: Upload XCFrameworks to S3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
           aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
           aws_bucket: 'pd-ios-spm-binaries'
           source_dir: ${{ env.xcframeworks_output_path }}
           destination_dir: 'ParallaxPagerView'
